FROM python:3.10-slim

WORKDIR /app

COPY api/api_tfidf ./api_tfidf
COPY models/tfidf ./model

RUN pip install --no-cache-dir fastapi uvicorn scikit-learn joblib prometheus_client

EXPOSE 8001

CMD ["uvicorn", "api_tfidf.main:app", "--host", "0.0.0.0", "--port", "8001"]
